### ISSUE TITLE
did it pass all the test case?

### ISSUE THREAD

**Issue by banty306** [b00401062/b00401062.github.io#2]
I even tried the same logic using c++ but it didn't pass the test case. Did you passed all the test cases. 

我什至使用c ++尝试了相同的逻辑，但未通过测试用例。 您是否通过了所有测试用例。

**Comment by b00401062** [comment]
What question are you referring to? I suppose it's the ongoing contest currently held on CodeChef you are talking about. In a nutshell, reimplementing the same logic in C/C++ usually gets me pass the test cases.

**Comment by banty306** [comment]
Yes I am talking about the ongoing contest on codechef actually I implemented the same logic but getting error again and again so I was looking for the reason.  Can you help me with the hint of adashop2 problem that's where I am stuck.

**Comment by b00401062** [comment]
Before staring to traverse the chessboard, the bishop first returns to (1,1) if the bishop is not at (1,1) already. From (1,1), traversal can be done well within 20 steps. I passed this problem with Java implementation without difficulty. Anyway, you are welcomed to show me your implementation if you don't mind, and let's see if there's any problem in it.

**Comment by banty306** [comment]
i even copied your code and tried but still i am getting error
![image](https://user-images.githubusercontent.com/45758942/76358290-416d6800-633f-11ea-8261-04dd7b8aef67.png)
can you help me with the exact solution because it is much needed for my exam i will try to understand the concept later. I would really appreciate your help.
